### ISSUE TITLE
Site returning 502 responses

### ISSUE THREAD

**Issue by declanvk** [biox/vore#5]
Sorry I didn't know of a better place to post this! Thank you for running vore.website, it sparked my interest in RSS feeds.

Recently (within the last month or so?) the website has started returning 502 responses:

```
HTTP/2 502 
server: Caddy
content-length: 0
date: Wed, 07 Aug 2024 18:45:32 GMT
X-Firefox-Spdy: h2


```

I had a bunch of links saved that I'd like to access, either from the website again or just a data dump if possible? I totally understand if you're too busy or not interested in running the site any longer. Thanks!

**Comment by biox** [comment]
heyhey! thanks for writing - my intent is to get the site running again, but i can't promise when - i'm in the middle of a big move currently & just don't have time to troubleshoot things. there's currently some sort of memory leak that makes vore explode, and i think it has something to do with certain feeds - the normal memory profile of vore is pretty minimal & i saw chunks of 1+GB being allocated during startup.

i blew the memory of my VM up to 8GB and still, no luck - memory exhaustion. hopefully within the next few days i'll have some time to dig deeper.

**Comment by declanvk** [comment]
Thanks for taking a look and good luck with your move!

**Comment by biox** [comment]
thanks! it went very well. i managed to find time to fix this issue - classic `http.Client` timeout consuming all of my goroutines leading to memory explosion sorta bug. x_x
